apiVersion: apps/v1
kind: Deployment
metadata:
  name: drogue-gateway
  labels:
    app: drogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drogue
  template:
    metadata:
      labels:
        app: drogue
    spec:
      hostNetwork: true
      containers:
      - name: drogue-device
        image: quay.io/dejanb/drogue-gateway:latest
        command: ["./entrypoint.sh"]
        args: ["app/gateway.py"]
        env:
        - name: TOKEN
          value: e5571d4f4377707a
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/var/lib/bluetooth/mesh/"
            name: mesh-volume
          - mountPath: /root/.config/meshcfg/
            name: mesh-config
          - mountPath: /var/run/dbus/system_bus_socket
            name: dbus-socket
      volumes:
      - name: mesh-volume
        hostPath:
          path: /home/dejanb/burrboard/gateway/deploy/bluez/example/mesh/
      - name: mesh-config
        hostPath:
          path: /home/dejanb/burrboard/gateway/deploy/bluez/example/meshcfg
      - name: dbus-socket
        hostPath:
          path: /var/run/dbus/system_bus_socket
