apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: burrboard-triggertemplate
  namespace: drogue-ajour
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: burrboard-rev2-run-
        namespace: $(tt.params.namespace)
      spec:
        params:
          - name: GIT_REPO
            value: $(tt.params.gitrepositoryurl)
          - name: GIT_REVISION
            value: $(tt.params.gitrevision)
          - name: PROJECT_PATH
            value: firmware/application
          - name: IMAGE
            value: burrboard-rev2
          - name: CARGO_BUILD_ARGS
            value: "--features rev2,defmt,gatt_only"
        pipelineRef:
          name: oci-firmware
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: build
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: burrboard-rev3-run-
        namespace: $(tt.params.namespace)
      spec:
        params:
          - name: GIT_REPO
            value: $(tt.params.gitrepositoryurl)
          - name: GIT_REVISION
            value: $(tt.params.gitrevision)
          - name: PROJECT_PATH
            value: firmware/application
          - name: IMAGE
            value: burrboard-rev3
          - name: CARGO_BUILD_ARGS
            value: "--features rev3,defmt,gatt_only"
        pipelineRef:
          name: oci-firmware
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: build
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: burrboard-rev3-5-run-
        namespace: $(tt.params.namespace)
      spec:
        params:
          - name: GIT_REPO
            value: $(tt.params.gitrepositoryurl)
          - name: GIT_REVISION
            value: $(tt.params.gitrevision)
          - name: PROJECT_PATH
            value: firmware/application
          - name: IMAGE
            value: burrboard-rev3-5
          - name: CARGO_BUILD_ARGS
            value: "--features rev3.5,defmt,gatt_first"
        pipelineRef:
          name: oci-firmware
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: build
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: burrboard-pipelinebinding
  namespace: drogue-ajour
spec:
  params:
    - name: gitrevision
      value: main
    - name: namespace
      value: drogue-ajour
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: burrboard-listener
  namespace: drogue-ajour
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
      - ref: burrboard-pipelinebinding
      template:
        ref: burrboard-triggertemplate
