apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: device-simulator
spec:
  output:
    to:
      kind: ImageStreamTag
      name: device-simulator:latest
  source:
    contextDir: digital-twin/simulation/device
    git:
      ref: main
      uri: https://github.com/drogue-iot/burrboard
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
    - type: ConfigChange
