kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: kafka
  namespace: burrboard
spec:

  kafka:
    authorization:
      type: simple
      superUsers:
        - burr-admin
    config:
      log.message.format.version: "2.8"
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
      auto.create.topics.enable: false
    listeners:
      - name: plain
        tls: false
        port: 9092
        type: internal
        authentication:
          type: scram-sha-512
      - name: tls
        tls: true
        port: 9093
        type: internal
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: route
        authentication:
          type: scram-sha-512
        tls: true
        configuration:
          brokerCertChainAndKey:
            certificate: tls.crt
            key: tls.key
            secretName: cluster-tls

    replicas: 1
    storage:
      deleteClaim: true
      size: 10Gi
      type: persistent-claim
    version: "2.8.0"

  zookeeper:
    replicas: 1
    storage:
      deleteClaim: true
      size: 1Gi
      type: persistent-claim

  entityOperator:
    topicOperator:
      watchedNamespace: burrboard
    userOperator:
      watchedNamespace: burrboard

