= Digital Twin data format

We are using [Eclipse Ditto](https://www.eclipse.org/ditto/) as digital twin solution. So most of the options that
the Ditto API provides should just work.

We will also create a configuration to stream all changes out into a Kafka topic.

== Thing definition

=== Introduction

The following is a simple example of the data format.

[source,json]
----
{
  "policyId": "ctron-test-ditto:default",
  "thingId": "ctron-test-ditto:device1",
  "features": {
    "accelerometer": {
      "properties": {              <1>
        "x": 4.982628199928287,
        "y": 0.2013457093437021,
        "z": 257.23714141524886,
        "fooBar": 120
      },
      "desiredProperties": {       <2>
        "fooBar": 123
      }
    }
  }
}
----
<1> Properties reported by the device.
<2> Properties scheduled to be sent to the device.

The `fooBar` property is just in this example to illustrate the "desired properties" feature. In the following examples
the simple version will be used to keep things short and simple. However, actually the full state is transmitted.

=== Full definition

[source,json]
----
{
  "policyId": "ctron-test-ditto:default",
  "thingId": "ctron-test-ditto:device1",
  "features": {
    "state": {
      "properties": {
        "deviceMode": 1,
        "firmwareRevision": 123,
        "reportInterval": 5000
      },
      "desiredProperties": {
        "deviceMode": 1,
        "firmwareRevision": 123,
        "reportInterval": 5000
      }
    },
    "accelerometer": {
        "properties": {
            "x": 4.982628199928287,
            "y": 0.2013457093437021,
            "z": 257.23714141524886
        }
    },
    "temperature": {
      "properties": {
        "value": 23.0
      }
    },
    "light" : {
      "properties": {
        "value": 1200
      }
    },
    "buttons" : {
      "properties": {
        "A": 0,  <1>
        "B": 0   <2>
      }
    },
    "leds": {
      "properties": {
        "1": false,
        "2": false,
        "3": false,
        "4": false
      },
      "desiredProperties": {
        "1": false,
        "2": false,
        "3": false,
        "4": false
      }
    }
  }
}
----
<1> Counter value for Button A
<2> Counter value for Button B

== WebSockets streaming

See: https://www.eclipse.org/ditto/httpapi-protocol-bindings-websocket.html

To simply subscribe to all events send `START-SEND-EVENTS` once the connection is established: https://www.eclipse.org/ditto/httpapi-protocol-bindings-websocket.html#request-events

The device state is wrapped in the WebSocket message as follows:

[source,json]
----
{
  "topic": "ctron-test-ditto/device1/things/twin/events/modified",  <1>
  "headers": {
    "response-required": false,
    "application": "ctron-test-ditto",
    "correlation-id": "1e704cf0-95a6-4d87-8543-6bcca2e17980",
    "device": "device1",
    "requested-acks": [],
    "ditto-originator": "pre-authenticated:drogue-cloud",
    "version": 2,
    "content-type": "application/json"
  },
  "path": "/",                                                      <2>
  "value": {                                                        <3>
    "thingId": "ctron-test-ditto:device1",
    "policyId": "ctron-test-ditto:default",
    "features": {
      "accelerometer": {
        "properties": {
          "x": -0.5068793510061224,
          "y": 0.5435910539029908,
          "z": 223.22327038834564
        }
      }
    }
  },
  "revision": 15519,
  "timestamp": "2022-01-21T11:34:56.221792720Z"
}
----
<1> The topic the events was sent out to. A mix of ID, type, subject/verb.
<2> The path the update took place (for `things/twin/events/modified`)
<3> The value of the update, for `path=/` this is the full state.

**Note**: After sending the start command, you will receive an "ack". This is not formatted as JSON, but plain text.

== Kafka topic

The events in the Kafka topic will be encoded as Cloud Events, wrapping the actual Ditto events as JSON data.

== HTTP API (get)

You can get the current state of thing like this (Application: `ctron-test-ditto`, Device: `device1`):

[source]
----
http -v GET https://ditto-drogue-dev.apps.wonderful.iot-playground.org/api/2/things/ctron-test-ditto:device1 "Authorization:Bearer $(drg whoami -t)"
----

The metadata goes into the headers:

[source]
----
HTTP/1.1 200 OK
cache-control: private
content-length: 191
content-type: application/json
correlation-id: 15502f28-686b-4c18-b9e3-467e99f88e48
date: Fri, 21 Jan 2022 11:42:09 GMT
ditto-originator: keycloak:f79dd520-707f-444b-bb50-553f81435cdc
etag: "rev:15528"                                                 <1>
response-required: false
version: 2
----
<1> The revision number, encoded in an ETag.

While the actual state is in the payload:

[source,json]
----
{
    "features": {
        "accelerometer": {
            "properties": {
                "x": -0.4864513375357738,
                "y": 0.4960569782021919,
                "z": 223.2258574552859
            }
        }
    },
    "policyId": "ctron-test-ditto:default",
    "thingId": "ctron-test-ditto:device1"
}
----
