[package]
edition = "2021"
name = "burrboard-firmware"
version = "0.1.0"
authors = ["Ulf Lilleengen <lulf@redhat.com>"]
resolver = "2"

[dependencies]
defmt = { version = "0.3", optional = true }
defmt-rtt = { version = "0.3", optional = true }
panic-probe = { version = "0.3", features = ["print-defmt"], optional = true }

# For uart logging
log = { version = "0.4", optional = true }
panic-reset = { version = "0.1.1", optional = true }

cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.7"

embassy = { version = "0.1.0", default-features = false }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["nrf52840", "time-driver-rtc1", "gpiote", "unstable-pac", "unstable-traits"]}
drogue-device = { version = "0.1.0", default-features = false, features = ["time"] }
embassy-boot-nrf = { git = "https://github.com/lulf/embassy.git", branch = "embassy-boot", features = ["softdevice"] }
embedded-hal = { version = "0.2", features = ["unproven"] }
futures     = { version = "0.3.17", default-features = false, features = ["async-await"] }

nrf-softdevice = { version = "0.1.0", git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "c63cb6359964926470e424fc899fa5e15612a5e6", features = ["ble-peripheral", "ble-central", "ble-gatt-server", "s140", "nrf52840"] }
nrf-softdevice-s140 = { version = "0.1.0", git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "c63cb6359964926470e424fc899fa5e15612a5e6" }
embedded-storage = { git = "https://github.com/embassy-rs/embedded-storage.git", branch = "embassy" }
embedded-storage-async = { git = "https://github.com/embassy-rs/embedded-storage.git", branch = "embassy" }

bitflags = { version = "1.3", default-features = false }
lsm6ds33 = "0.2.0"
heapless = "0.7"

[features]
default = ["panic-reset"]
gatt = []
lsm = []
defmt = [
      "dep:defmt",
      "defmt-rtt",
      "embassy/defmt",
      "drogue-device/defmt",
      "panic-probe",
      "nrf-softdevice/defmt",
]
log = [
    "dep:log",
    "panic-reset",
]

[patch.crates-io]
embassy = { git = "https://github.com/lulf/embassy.git", branch = "embassy-boot"}
embassy-nrf = { git = "https://github.com/lulf/embassy.git", branch = "embassy-boot"}
drogue-device = { git = "https://github.com/drogue-iot/drogue-device.git", rev = "c53431c07aaa351f9d37a387af2df0aec52b6b82" }
#drogue-device = { path = "../../drogue-iot/drogue-device/device" }
#embassy = { path = "../../embassy/embassy" }
#embassy-nrf = { path = "../../embassy/embassy-nrf" }
#embassy-boot-nrf = { path = "../../embassy/embassy-boot/nrf" }
