name: Gateway Image CI

on:
  push:
    branches: [ main ]
    paths:
      - gateway/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Get the repository's code
    - 
      name: Checkout
      uses: actions/checkout@v2
    # https://github.com/docker/setup-qemu-action
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    # https://github.com/docker/setup-buildx-action
    - 
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    # Login to the repo
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # build and push images
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: gateway/
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{github.repository}}/drogue-gateway:latest
